### ISSUE TITLE
Hide actions before player's previous turn until end of game screen 

### ISSUE THREAD

**Issue by zelmor** [rally-the-troops/pax-pamir#1]
A big part of Pamir is holding onto cards in your hands, waiting for the opportunity to play an unforseen move you have been holding onto since the first turns. 

With the current implementation one can track the cards in the opponents' hand, giving perfect information of the board state. I would like to propose the default setting to hide parts of the log before the last move done by the player. This way one can see what players did in the last rounds, but not what they light have in their hands from several turns ago. 

The completely log should only be visible after the the game ends.

**Comment by vandamm** [comment]
Truth is, in real game the cards you take from the market are open information and a person with good memory can track which cards everyone has in their hands. It's complicated, but not impossible. The log just makes it way easier.
