### ISSUE TITLE
Bug with buying a dominance check

### ISSUE THREAD

**Issue by medinacode** [rally-the-troops/pax-pamir#3]
Blue can't buy the dominance check card in column 3 even though blue has 8 rupees.

<img width="1229" alt="Screen Shot 2022-08-02 at 9 33 24 AM" src="https://user-images.githubusercontent.com/1844514/182388371-60460597-b75c-4821-8ac3-645542a52748.png">

https://rally-the-troops.com/pax-pamir/play:8457

**Comment by ccxvii** [comment]
You've forgotten this rule:

**"If you place a rupee on a market card for any reason, you may not purchase that card this turn."**

When you used Gift you placed a coin on the Dominance Check card. That is why you cannot buy it.

**Comment by medinacode** [comment]
Good catch, thank you!
