### ISSUE TITLE
When paying back leverage when off-turn, not given opportunity to discard and can result with having negative money

### ISSUE THREAD

**Issue by a-harris** [rally-the-troops/pax-pamir#4]
https://www.rally-the-troops.com/pax-pamir/play:8776:Gray

![image](https://user-images.githubusercontent.com/41584708/183142867-6cb89ddf-74fc-49cd-9f32-e48cfa4aee09.png)

![image](https://user-images.githubusercontent.com/41584708/183142932-d9f30c8a-94c2-404e-acd0-45d71d510984.png)

**Comment by a-harris** [comment]
When playing your turn, after taking one action it forces you to resolve the leverage.

**Comment by ccxvii** [comment]
Right, this situation can arise when the Riot event cards discard your cards.

Normally you're forced to pay back leverage after an action, but here we should also do the same check after a Riot event has resolved.
