### ISSUE TITLE
Allow user to zoom in on the card to read finer print such as the special abilities

### ISSUE THREAD

**Issue by crowmagnumb** [rally-the-troops/pax-pamir#5]
It's too difficult for me to see the finer print on the cards. So I find myself right clicking and choosing open in new tab, for which it does such that I can read the card. But it would be nice say if after hovering cursor over the card for a couple of seconds the card showed up larger in a popup window, or something like that. Cheers! Thanks for all your work on this!

**Comment by ccxvii** [comment]
Have you tried holding down the shift key while hovering over a card?

It's a common feature across the games on RTT, where holding shift will often zoom in on small details.
This is mentioned on the /about page, as well as a few other tips & tricks that can come in handy.
